version: "3.8"
services:
  backend-prod:
    container_name: levain-backend-prod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    expose:
      - 80