FROM openjdk:17-alpine

WORKDIR /app

ARG JAR_FILE=./build/libs/mendolong-1.0.0.jar

COPY ${JAR_FILE} mendolong.jar

ENV PROFILES prod

EXPOSE 80

ENTRYPOINT ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/mendolong.jar"]
