= 멘도롱 주멍 REST Docs
https://levains-house.com
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[Overview]]
== Overview

[[Overview-host]]
=== Host

|===
| 환경 | Host

| Beta
| `https://github.com/CokeLee777`

| Production
| `AWS ECS(Elastic Container Service)`
|===

[[overview-http-status-codes]]
=== HTTP status codes

|===
| 상태 코드 | 설명

| `200 OK`
| 성공

| `201 CREATED`
| 생성

| `400 Bad Request`
| 잘못된 요청

| `401 Unauthorized`
| 비인증 상태

| `404 Not Found`
| 존재하지 않는 요청 리소스

| `500 Internal Server Error`
| 서버 에러
|===

[[overview-error-response]]
=== HTTP Error Response
operation::common-doc-controller-test/error[snippets='http-response,response-fields']

[[User-API]]
== User API

[[사용자-로그인]]
=== 사용자 로그인
operation::user-controller-test/sign-in[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[사용자-주소-입력]]
=== 사용자 주소 입력
operation::user-controller-test/sign-in-address[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']

[[Item-API]]
== Item API

[[추천-주멍-조회]]
=== 추천 주멍 조회
operation::item-controller-test/search[snippets='http-request,query-parameters,http-response,response-body,response-fields']

[[나의-주멍-및-너의-주멍-등록]]
=== 나의 주멍 및 너의 주멍 등록
operation::item-controller-test/register[snippets='http-request,request-parts,request-part-itemInfo-fields,http-response,response-body,response-fields']

[[나의-주멍-조회]]
=== 나의 주멍 조회
operation::item-controller-test/search-my-list[snippets='http-request,request-body,query-parameters,http-response,response-body,response-fields']

[[나의-주멍-거래내역-수정]]
=== 나의 주멍 거래내역 수정
operation::item-controller-test/update-trade-status[snippets='http-request,request-body,request-fields,http-response,response-body,response-fields']